language: ruby
rvm:
  - 2.5.3
os: osx
osx_image: xcode10.1
branches:
  only:
    - master

# unit tests
before_install:
  - gem update --system

install:
  - bundle install

jobs:
  include:
    - stage: run framework unit tests
      script:
        - rake test:msdkui_unit

    - stage: run demo app unit tests
      script:
        - rake test:demo_app_unit

    - stage: publish unit test coverage
      script:
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF ios -J 'MSDKUI_Demo_Tests' -J 'MSDKUI_Tests'